### ISSUE TITLE
Status des PlugIns

### ISSUE THREAD

**Issue by GaRaOne** [eledia/eledia_usercleanup#1]
Das PlugIn wird nicht mehr unter https://moodle.org/plugins/view.php?plugin=block_eledia_usercleanup gelistet und die letzte Version hier im Repo ist fuer Moodle 3.6.

Ist das Projekt noch aktiv?
Gibt es Alternativen?

**Comment by eledia** [comment]
Auf moodle.org wurde es leider nie freigeschalet. Aber wir planen das in den nächsten Wochen hier auf 3.9 zu veröffentlichen.

**Comment by GaRaOne** [comment]
vielen dank fuer die info
